debug: false
server:
    port: 8080

spring:
    http:
      encoding:
        charset: UTF-8
        force: true
        enabled: true
      multipart:
        max-file-size: 1024Mb
        max-request-size: 2048Mb
    freemarker:
        template-loader-path:
        - /templates/
        - file:./templates/
        cache: false
        settings:
            classic_compatible: true #处理空值
            template_exception_handler: rethrow
            template_update_delay: 0
            datetime_format: yyyy-MM-dd HH:mm
            number_format: 0.##
            
    datasource:
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost/db_mblog?useUnicode=true&allowMultiQueries=true
        username: root
        password: 123456
    mail:
        host: smtp.mtons.com
        username: example@mtons.com
        password: Example2018
        port: 25
        properties:
            mail.smtp.auth: true
    
#mybatis文件指定
mybatis:
    mapper-locations: classpath*:mapper/*.xml
    
    type-aliases-package: com.unzen.common.core.persist.entity
 
#配置分页插件pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql   

#log4j2配置地址
logging:
  config: src/main/resources/log4j2-spring.xml
    
site.store.root: E:/worksapce/mtons-mblog-master/data/mblog
# 存储模式, 可选值 absolute / relative
site.store.repo: absolute

# 是否开启资源域名
site.store.domain: false
